[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.5.0",
    "streamlit>=1.52.0",
    "xgboost>=3.1.2",
]
